reports/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from . import views

app_name = "reports"

urlpatterns = [
    path(
        "children/<str:slug>/reports",
        views.ChildReportList.as_view(),
        name="report-list",
    ),
    path(
        "children/<str:slug>/reports/bmi/bmi/",
        views.BMIChangeChildReport.as_view(),
        name="report-bmi-change-child",
    ),
    path(
        "children/<str:slug>/reports/changes/amounts/",
        views.DiaperChangeAmounts.as_view(),
        name="report-diaperchange-amounts-child",
    ),
    path(
        "children/<str:slug>/reports/changes/lifetimes/",
        views.DiaperChangeLifetimesChildReport.as_view(),
        name="report-diaperchange-lifetimes-child",
    ),
    path(
        "children/<str:slug>/reports/changes/types/",
        views.DiaperChangeTypesChildReport.as_view(),
        name="report-diaperchange-types-child",
    ),
    path(
        "children/<str:slug>/reports/changes/intervals/",
        views.DiaperChangeIntervalsChildReport.as_view(),
        name="report-diaperchange-intervals-child",
    ),
    path(
        "children/<str:slug>/reports/feeding/amounts/",
        views.FeedingAmountsChildReport.as_view(),
        name="report-feeding-amounts-child",
    ),
    path(
        "children/<str:slug>/reports/head-circumference/head-circumference/",
        views.HeadCircumferenceChangeChildReport.as_view(),
        name="report-head-circumference-change-child",
    ),
    path(
        "children/<str:slug>/reports/height/height/",
        views.HeightChangeChildReport.as_view(),
        name="report-height-change-child",
    ),
    path(
        "children/<str:slug>/reports/feeding/duration/",
        views.FeedingDurationChildReport.as_view(),
        name="report-feeding-duration-child",
    ),
    path(
        "children/<str:slug>/reports/pumping/amounts/",
        views.PumpingAmounts.as_view(),
        name="report-pumping-amounts-child",
    ),
    path(
        "children/<str:slug>/reports/feeding/intervals/",
        views.FeedingIntervalsChildReport.as_view(),
        name="report-feeding-intervals-child",
    ),
    path(
        "children/<str:slug>/reports/sleep/pattern/",
        views.SleepPatternChildReport.as_view(),
        name="report-sleep-pattern-child",
    ),
    path(
        "children/<str:slug>/reports/sleep/totals/",
        views.SleepTotalsChildReport.as_view(),
        name="report-sleep-totals-child",
    ),
    path(
        "children/<str:slug>/reports/temperature/temperature/",
        views.TemperatureChangeChildReport.as_view(),
        name="report-temperature-change-child",
    ),
    path(
        "children/<str:slug>/reports/tummy-time/duration/",
        views.TummyTimeDurationChildReport.as_view(),
        name="report-tummy-time-duration-child",
    ),
    path(
        "children/<str:slug>/reports/weight/weight/",
        views.WeightChangeChildReport.as_view(),
        name="report-weight-change-child",
    ),
    path(
        "children/<str:slug>/reports/weight/<sex>/",
        views.WeightChangeChildReport.as_view(),
        name="report-weight-change-child-sex",
    ),
]

reports/templates/reports/diaperchange_intervals.html
{% extends 'reports/report_base.html' %}
{% load i18n %}

{% block title %}{% trans "Diaper Change Intervals" %} - {{ object }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item active" aria-current="page">{% trans "Diaper Change Intervals" %}</li>
{% endblock %}

reports/templates/reports/feeding_intervals.html
{% extends 'reports/report_base.html' %}
{% load i18n %}

{% block title %}{% trans "Feeding Intervals" %} - {{ object }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item active" aria-current="page">{% trans "Feeding Intervals" %}</li>
{% endblock %}

reports/templates/reports/report_list.html
{% extends 'reports/base.html' %}
{% load breadcrumb i18n static %}

{% block title %}{% trans "Reports" %} - {{ object }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item font-weight-bold">
        {% child_quick_switch object 'reports:report-list' %}
    </li>
    <li class="breadcrumb-item active" aria-current="page">{% trans "Reports" %}</li>

{% endblock %}

{% block content %}
    <div class="container-fluid">
        <h1>Reports</h1>
        <div class="reports-list list-group">
            <a href="{% url 'reports:report-bmi-change-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Body Mass Index (BMI)" %}</a>
            <a href="{% url 'reports:report-diaperchange-amounts-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Diaper Change Amounts" %}</a>
            <a href="{% url 'reports:report-diaperchange-types-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Diaper Change Types" %}</a>
            <a href="{% url 'reports:report-diaperchange-intervals-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Diaper Intervals" %}</a>
            <a href="{% url 'reports:report-diaperchange-lifetimes-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Diaper Lifetimes" %}</a>
            <a href="{% url 'reports:report-feeding-amounts-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Feeding Amounts" %}</a>
            <a href="{% url 'reports:report-feeding-duration-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Feeding Durations (Average)" %}</a>
            <a href="{% url 'reports:report-feeding-intervals-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Feeding Intervals" %}</a>
            <a href="{% url 'reports:report-head-circumference-change-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Head Circumference" %}</a>
            <a href="{% url 'reports:report-height-change-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Height" %}</a>
            <a href="{% url 'reports:report-pumping-amounts-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Pumping Amounts" %}</a>
            <a href="{% url 'reports:report-sleep-pattern-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Sleep Pattern" %}</a>
            <a href="{% url 'reports:report-sleep-totals-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Sleep Totals" %}</a>
            <a href="{% url 'reports:report-temperature-change-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Temperature" %}</a>
            <a href="{% url 'reports:report-tummy-time-duration-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Tummy Time Durations (Sum)" %}</a>
            <a href="{% url 'reports:report-weight-change-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Weight" %}</a>
            <a href="{% url 'reports:report-weight-change-child-sex' object.slug 'boy' %}" class="list-group-item list-group-item-action">{% trans "WHO Weight Percentiles for Boys in kg" %}</a>
            <a href="{% url 'reports:report-weight-change-child-sex' object.slug 'girl' %}" class="list-group-item list-group-item-action">{% trans "WHO Weight Percentiles for Girls in kg" %}</a>
        </div>
    </div>
{% endblock %}